# Splitting the PUBG Data(4446966 rows, 29 columns) into Train and Test by 80%-20%

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from google.colab import drive
import warnings
warnings.filterwarnings("ignore")

In [ ]:
drive.mount('/content/drive/')

Mounted at /content/drive/

In [ ]:
Train = pd.read_csv('/content/drive/MyDrive/PUBG-finish-placement-prediction/Original_data/train_V2.csv')
Train.head()

               Id         groupId  ... winPoints  winPlacePerc
0  7f96b2f878858a  4d4b580de459be  ...      1466        0.4444
1  eef90569b9d03c  684d5656442f9e  ...         0        0.6400
2  1eaf90ac73de72  6a4a42c3245a74  ...         0        0.7755
3  4616d365dd2853  a930a9c79cd721  ...         0        0.1667
4  315c96c26c9aac  de04010b3458dd  ...         0        0.1875

[5 rows x 29 columns]

In [ ]:
X = Train.drop(columns='winPlacePerc')
y = Train['winPlacePerc']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
X_train

                     Id         groupId  ... weaponsAcquired  winPoints
2301310  dd1abf8c8dea06  874c02ce3e8883  ...               0          0
3891238  fc609144bd1681  d64fdc706a385e  ...               1          0
3954389  4162f2e84a85fd  4ca0a106852af3  ...               3       1523
3518157  77f9aefafd79b7  2a80a0320990bc  ...               2       1532
1946211  5eacc6e736d0b3  17b1572f2599d5  ...               6       1569
...                 ...             ...  ...             ...        ...
824152   0c24dab84b73fe  56c3c5e4343759  ...               6       1567
1263027  131e18b3075887  56f799406194b7  ...               5       1500
243691   a30fb1145d8266  8d8377f3024d8a  ...               5       1498
2621753  6d7a831bb651f2  346ea3d561c44e  ...               5          0
2377392  35b0776ae958d8  c08650bf69fd8e  ...               5          0

[3557572 rows x 28 columns]

In [ ]:
X_test

                     Id         groupId  ... weaponsAcquired  winPoints
1932059  3819823802f48a  f0fd309f8ca457  ...               5       1455
3294888  aa439f81e8792b  c83cc7dcb364cd  ...               5       1517
3403766  5284c4d2d9183c  7bfd6bd25707fd  ...               3          0
739777   c15709d34368e3  4e6a9999406061  ...               2          0
191251   d749a74a11eb0a  f2a554bfed0c58  ...               3          0
...                 ...             ...  ...             ...        ...
667687   8758ccc2119cb4  4676bae6e20eaf  ...               7       1523
931011   12f94992da4dc7  907492739ae47e  ...               9       1547
781083   5c59fceda16050  3affb4c10c60e6  ...               5       1458
620846   c38b7f76467a12  ab0ef1b21c2c19  ...               5       1545
1327786  0d2349d0978e99  ceecd33f4d5ed0  ...               7       1488

[889394 rows x 28 columns]

In [ ]:
y_train

2301310    0.0612
3891238    0.0769
3954389    0.8276
3518157    0.7857
1946211    0.8519
            ...
824152     0.6739
1263027    0.7778
243691     0.8519
2621753    0.7826
2377392    0.7143
Name: winPlacePerc, Length: 3557572, dtype: float64

In [ ]:
y_test

1932059    0.6522
3294888    0.9032
3403766    0.2766
739777     0.2963
191251     0.5714
            ...
667687     0.5556
931011     0.9778
781083     0.3929
620846     0.2692
1327786    0.9200
Name: winPlacePerc, Length: 889394, dtype: float64

In [ ]:
Train_data = pd.concat([X_train,y_train], axis=1)

In [ ]:
Train_data.head()

                     Id         groupId  ... winPoints  winPlacePerc
2301310  dd1abf8c8dea06  874c02ce3e8883  ...         0        0.0612
3891238  fc609144bd1681  d64fdc706a385e  ...         0        0.0769
3954389  4162f2e84a85fd  4ca0a106852af3  ...      1523        0.8276
3518157  77f9aefafd79b7  2a80a0320990bc  ...      1532        0.7857
1946211  5eacc6e736d0b3  17b1572f2599d5  ...      1569        0.8519

[5 rows x 29 columns]

In [ ]:
Test_data = pd.concat([X_test,y_test], axis=1)

In [ ]:
Test_data.head()

                     Id         groupId  ... winPoints  winPlacePerc
1932059  3819823802f48a  f0fd309f8ca457  ...      1455        0.6522
3294888  aa439f81e8792b  c83cc7dcb364cd  ...      1517        0.9032
3403766  5284c4d2d9183c  7bfd6bd25707fd  ...         0        0.2766
739777   c15709d34368e3  4e6a9999406061  ...         0        0.2963
191251   d749a74a11eb0a  f2a554bfed0c58  ...         0        0.5714

[5 rows x 29 columns]

In [ ]:
Train_data.to_csv('/content/drive/MyDrive/PUBG-finish-placement-prediction/Train_data.csv', index=False)

In [ ]:
Test_data.to_csv('/content/drive/MyDrive/PUBG-finish-placement-prediction/Test_data.csv', index=False)